### ISSUE TITLE
Confusing column row area types

### ISSUE THREAD

**Issue by tuck0066** [tuck0066/components-on-a-grid#1]
@hellachella

I think I am trying to mash all the types together and I've created a huge mess.

**Comment by hellachella** [comment]
Please consolidate your CSS into one file so we can have a look.

@mackenzierose

**Comment by hellachella** [comment]
### In your body CSS:
```
body {
  margin: 0;
  display: grid;
  grid-template-columns: 1fr 1fr 1fr; 
```
remove one of the columns. You have three fractions making it a three-column grid. The design is a two-column grid:
```
grid-template-columns: 1fr 1fr; 
```
remove the following:
```
grid-template-rows: 1fr 4rem; 
```
 
Set up grid-template area here in body
  ```
 grid-template-areas:
 "banner banner"
 "col1 col2";
```
 then go and assign the pano and the figures to those spots using their names
 for example:
```
 .pano {
 grid-area: banner;
```
 Do this first and then we can move on.

**Comment by MacKenzieRose** [comment]
Hey @tuck0066!

So you're getting the hang of this completely new system of building webpages, so congrats. I'm seeing a lot of good stuff for where you're using `columns` and `rows`, which is totally different than the old system with modulifier etc.

The big thing for this assignment is that we're learning to use this new system of blocking out parts of our site, called `grid-template-areas`. I can see the start of this in your code! (for example, around line 66, you've written `grid-area: main` which is assigning the `h2` to that area of the grid. BUT! We haven't created any areas yet, so these bits of code don't yet do anything! So let's get that set up first)

Does this look familiar?
<img width="711" alt="image" src="https://user-images.githubusercontent.com/19557909/94023933-cc1a2f80-fd84-11ea-972f-d86a81a3a493.png">

This is how the grid works for this assignment, where we have a 2x2 system. If you look at your code, you currently have 3x3 system, so we're going to make the following changes: 

## 1. Replace `grid-template-rows` on your body tag (~line 25) with:
`grid-template-areas:`
`"name1 name1"`
`"name2 name3";`

^^you don't have to use these names for the areas-- you can pick anything you want that will help you remember what or where they are

## 2. Reduce the number of template-columns (~line 24) by 1

## 3. To make all of your elements visible again (we have a few things that have hid off-page), delete the `grid-column` `grid-row` and `z-index` from your `nav` `h1` and `img` tags.

## 4. For your `nav ul` let's add `display: flex`


It won't look right at all yet, but this will get everything set up for you. Let me know when you get to this part, and then we'll start assigning stylings and sizes to everything 🙂 (make sure to commit your new code to Github, so I can see it)

**Comment by hellachella** [comment]
Let's start a trio message thread on Slack to keep consistent.
